apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/deployment.yaml
  - k8s/service.yaml
  - k8s/ingress.yaml

namespace: liatrio-interview-exercise

commonLabels:
  app: liatrio-interview-exercise
  managed-by: kustomize

images:
  - name: madisonewebb/liatrio-interview-exercise
    newName: madisonewebb28/liatrio_exercise_docker
    newTag: v1
