apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liatrio-interview-exercise
  labels:
    app: liatrio-interview-exercise
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: liatrio-interview-exercise.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: liatrio-interview-exercise
            port:
              number: 80
